// GENERATED by tools/manifest.mjs. Do not edit; run `npm run assets`.
import type { AssetEntry } from './types';

export const ASSETS = {
} as const satisfies Record<string, AssetEntry>;

export const LAYOUTS = {
} as const satisfies Record<string, string>;

export type AssetId = keyof typeof ASSETS;
export type LayoutId = keyof typeof LAYOUTS;
