// Emits src/assets/manifest.gen.ts: typed ids for every built asset and layout.
import fs from 'node:fs';
import path from 'node:path';
import { P, assetOutPath, isMain, listDefs, listFiles, toPosix } from './lib/common.mjs';

export function writeManifest() {
  const assets = listDefs()
    .filter(({ id }) => fs.existsSync(assetOutPath(id)))
    .map(({ id, category }) => `  ${JSON.stringify(id)}: { url: ${JSON.stringify(`assets/${id}.glb`)}, category: ${JSON.stringify(category)} },`);
  const layouts = listFiles(P.layoutsOut, '.json')
    .map((f) => toPosix(path.relative(P.layoutsOut, f)).replace(/\.json$/, ''))
    .map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(`layouts/${id}.json`)},`);

  const src = `// GENERATED by tools/manifest.mjs. Do not edit; run \`npm run assets\`.
import type { AssetEntry } from './types';

export const ASSETS = {
${assets.join('\n')}
} as const satisfies Record<string, AssetEntry>;

export const LAYOUTS = {
${layouts.join('\n')}
} as const satisfies Record<string, string>;

export type AssetId = keyof typeof ASSETS;
export type LayoutId = keyof typeof LAYOUTS;
`;
  fs.writeFileSync(P.manifest, src);
  return { assets: assets.length, layouts: layouts.length };
}

if (isMain(import.meta.url)) {
  const r = writeManifest();
  console.log(`manifest: ${r.assets} assets, ${r.layouts} layouts`);
}
