// Emits src/assets/manifest.gen.ts: typed ids for every built asset and layout,
// with each asset's generator metadata (see tools/lib/catalog.mjs).
import fs from 'node:fs';
import path from 'node:path';
import { readCatalog } from './lib/catalog.mjs';
import { P, isMain, listFiles, toPosix } from './lib/common.mjs';

export async function writeManifest() {
  const catalog = await readCatalog();
  const assets = Object.entries(catalog).map(([id, { category, meta }]) =>
    `  ${JSON.stringify(id)}: { url: ${JSON.stringify(`assets/${id}.glb`)}, category: ${JSON.stringify(category)}, meta: ${JSON.stringify(meta)} },`);
  const layouts = listFiles(P.layoutsOut, '.json')
    .map((f) => toPosix(path.relative(P.layoutsOut, f)).replace(/\.json$/, ''))
    .map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(`layouts/${id}.json`)},`);

  const src = `// GENERATED by tools/manifest.mjs. Do not edit; run \`npm run assets\`.
import type { AssetEntry } from './types';

export const ASSETS = {
${assets.join('\n')}
} as const satisfies Record<string, AssetEntry>;

export const LAYOUTS = {
${layouts.join('\n')}
} as const satisfies Record<string, string>;

export type AssetId = keyof typeof ASSETS;
export type LayoutId = keyof typeof LAYOUTS;
`;
  fs.writeFileSync(P.manifest, src);
  return { assets: assets.length, layouts: layouts.length };
}

if (isMain(import.meta.url)) {
  const r = await writeManifest();
  console.log(`manifest: ${r.assets} assets, ${r.layouts} layouts`);
}
